### ISSUE TITLE
Add Usersnap support

### ISSUE THREAD

**Issue by kjgarza** [datacite/akita#110]
Use something Similar to this: https://github.com/vercel/next.js/tree/canary/packages/next-plugin-google-analytics

Use the token from **repository finder**: https://usersnap.com/a/#/datacite/p/re3data-055a8e02
repository finder won't have usersnap decide in: https://docs.google.com/document/d/18vg46DC5Tvu2kOO0ZYhcZpNlNFx-K1xjcskAC6_DhH8/edit?ts=5f478f4f#

**Comment by mfenner** [comment]
I have started to work on Google Analytics support, the issue is #108.
