### ISSUE TITLE
Display of citations and references for individual DOIs

### ISSUE THREAD

**Issue by mfenner** [datacite/akita#12]
- [ ] Related Content Component

based on:
- https://github.com/crosscite/doi-metadata-search/issues/136
- https://github.com/datacite/datacite-components

**Comment by kjgarza** [comment]
question on this:

Shall we keep the same look in the citations/references lists? I think the old one looks a bit too crowded but it benefits of having a narrative in the description.  See below:

The old list of citations/references lists look list this :
![image](https://user-images.githubusercontent.com/1092861/88821382-e55a9180-d1c2-11ea-9235-ee3026e55ba7.png)



However, I think it we could remove the narrative and make it a bit cleaner (arguably). with something like this: 

![image](https://user-images.githubusercontent.com/1092861/88821751-5437ea80-d1c3-11ea-9d42-a7bb6ea792f7.png)

we might look loose of the relation type  (even when is implied in the list name)but all other content is still present.

What do you think?

**Comment by mfenner** [comment]
For the MVP, please show these lists exactly as lists of DOIs elsewhere in `akita`, including facets and search. We can add provenance information after the MVP.
