### ISSUE TITLE
Support ORCID Search & Link claiming in DataCite Commons

### ISSUE THREAD

**Issue by mfenner** [datacite/akita#122]
The overall approach of this epic is as follows:

### Goals
* Implement ORCID Search & Link claiming in a way that is compatible with our implementation in DataCite Search to allow a gradual transition to DataCite Commons
* show claims from the search & link service in DataCite Commons, not just the auto-update claims
* allow claiming of DOIs from all DOI registration agencies
* lay the foundation for further ORCID claiming features going forward, both for individual DOIs (e.g. affiliation, contributor role) and the ORCID record as a whole (e.g. employment, biography, external identifiers).

### Implementation
* use the single sign-on solution by the Profiles service
* use the Profiles claims API
* implement the backend via the GraphQL API, as a layer on top of existing REST APIs
* the above requires GraphQL authentication and mutations

**Comment by richardhallett** [comment]
Closing as available in staging, some changes were made to the design to better support the state reflections in profiles.
Further comments see datacite/datacite#1175
