### ISSUE TITLE
Single Sign-On for DataCite Commons

### ISSUE THREAD

**Issue by mfenner** [datacite/akita#123]
Allow Commons users to sign in via the DataCite Single Sign-on service. This uses the existing workflow (authentication in Profiles, set permissions in subdomain via cookie with JWT), also used for example in DataCite Search.

![Bildschirmfoto 2020-09-10 um 09.29.35.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/1efb9987-05ab-4fb2-9836-36ad3586e79b)

**Comment by sarala** [comment]
@mfenner I'm not sure whether this workflow is working properly. I have signed in but I'm not able to signout from DataCite commons. Clicking on Commons Page points me to my page even after logging out. Clicking on the setting, takes me to the profiles page and asks to log in. So it looks like SignOut logs me out from profiles but it's not picked up in Commons. Is it possible to simplify this workflow?

**Comment by mfenner** [comment]
Returning to your page is expected after logging out. Does the menu bar say you are still logged in?

**Comment by sarala** [comment]
This is working for me now.
