### ISSUE TITLE
Make sharing in DataCite Commons more prominent

### ISSUE THREAD

**Issue by mfenner** [datacite/akita#125]
This aligns with the focus of the FREYA deliverable on providing functionality to end users, making it clearer what actions users can take (download, share, cite). Next big addition will be claim with ORCID.

![Bildschirmfoto 2020-09-06 um 19.25.59.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/1ef2284f-ebd1-448b-9bc6-289269c60897)

**Comment by mfenner** [comment]
I have made the following changes:

* renamed headings to download, cite and added share section
* moved share links from item footer to separate section
* added QR code
* grouped metadata downloads into two groups
* added content link for open content available via Unpaywall

**Comment by mfenner** [comment]
This is now mostly released and probably not needing much discussion. The exception is the QR Code, which can only be seen in stage.

**Comment by sarala** [comment]
@mfenner All looks good. I think you can take 'Email and Social Media' text out as it is quite obvious. I'm not entirely sure about the QR code. May be we can release and ask the community whether it's a useful feature.

**Comment by mfenner** [comment]
Removed "Email and Social Media" and "QR Code" headers.

![Bildschirmfoto 2020-09-26 um 18.17.59.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/bcb2ede8-899f-457a-9c84-d7b536985197)

**Comment by mfenner** [comment]
@sarala please also look at "Content via Unpaywall". Is that ok. Link is generated on the fly by calling the Unpaywall API. This only works for Crossref DOIs.
