### ISSUE TITLE
Show Employment in Person Record

### ISSUE THREAD

**Issue by mfenner** [datacite/akita#126]
From ORCID API. Link to organization if suitable identifiers (currently GRID or Crossref Funder ID) are available.

As part of this work we will add support for resolving GRID and Crossref Funder ID via DataCite Commons URL, e.g.

* https://commons.stage.datacite.org/grid.ac/institutes/grid.5335.0
* https://commons.stage.datacite.org/doi.org/10.13039/501100000735

![Bildschirmfoto 2020-09-06 um 19.28.20.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/8f29c996-d583-4c80-9bc3-9908ac4c9ba9)

**Comment by sarala** [comment]
This looks good.

May be we should list other Identifiers before the 'Share' section, and this can also be applied for organisations. For example: University of Cambridge has a lot which introduces a lot of white space in the middle. Is it possible to have a section for other identifiers and that's split into two columns?

**Comment by mfenner** [comment]
Is the comment for this particular issue?
