### ISSUE TITLE
use doi icon from academic icons

### ISSUE THREAD

**Issue by mfenner** [datacite/akita#132]
![Bildschirmfoto 2020-09-09 um 18.58.17.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/491a327b-d717-484c-9ace-9bf0dab9029a)

**Comment by mfenner** [comment]
Also adding the DataCite logo to the header

![Bildschirmfoto 2020-09-10 um 09.24.29.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/d3b5c851-1c5a-47ca-bdd1-60dd374c93a8)

**Comment by sarala** [comment]
All looks good. Logo doesn't have the two different colours. May be it would be nice to have the logo with the two colours.

**Comment by mfenner** [comment]
Logo is an icon font. We can use a proper logo instead if we want.

**Comment by mfenner** [comment]
Removing logo, leaving this for later discussions about DataCite header layout.
