### ISSUE TITLE
Add Outbound Link tracking

### ISSUE THREAD

**Issue by kjgarza** [datacite/akita#148]
DC Commons has many outbound links (share, links, profiles and export links, in multiple pages) that currently we do not track. It would be useful to know if users are actually using any of this links to understand what users are doing and define better features.

### Potential solution

Plausible can add this tracking by just changing the url of the script to track as in the docs:
https://plausible.io/blog/track-outbound-link-clicks#add-the-plausible-script-snippet-to-your-site

```
<script async defer data-domain="yourdomain.com" src="https://plausible.io/js/plausible.outbound-links.js"></script>
```

**Comment by mfenner** [comment]
@kjgarza why have you closed this issue?

**Comment by kjgarza** [comment]
I thought that as your messages in slack, you thought it was not a good idea to open the issue.
