### ISSUE TITLE
Query disappears from search box after clicking the tabs

### ISSUE THREAD

**Issue by kjgarza** [datacite/akita#154]
### Expected Behaviour

Search term should remain in the search box, unless the term is removed with the "X" icon

### Current Behaviour

query terms disappear as soon as one of the navigation taps is clicked.

### Steps to Reproduce

1. Search for term in any tab
2. click on another tab
3. see that the terms disappear

### Context (Environment)

the query seems to stay in the address bar but it disappears from the interface. See below.

![](https://gyazo.com/49a42f644bfdb9f783af23ac6067576a.gif)

**Comment by richardhallett** [comment]
Fixed and deployed.
