### ISSUE TITLE
Evaluate Charting Library

### ISSUE THREAD

**Issue by kjgarza** [datacite/akita#18]
From: https://docs.google.com/document/d/1yT5Kb4RRMyBsUxH3NfCBrv0wvpFQ3l0cHbR0eVBY5WA/edit

## options

I think semiotic looks nice, but there are better options. Semiotic has a minimal uptake. There is not a large community behind, and their approach doesn't, IMO, offer much when compared to other alternatives. 

I suggest we evaluate it against Vega. Vega has a broader community behind, and their approach its more maintainable for our development work(it’s totally declarative). Besides, it requires little to a non-learning curve. The evaluation can be done in “paper”.

## Criteria:

- Simples chart are simple to make
- Customizable
- React and d3 interact with the DOM

**Comment by mfenner** [comment]
* please explain "minimal uptake for semiotic", the GitHub repo for example has 2K stars https://github.com/nteract/semiotic
* why does the semiotic approach not offer much? One of our key criteria was to use something built specifically for react. Are there better alternatives for using d3 with react?
* please explain why using vega the "approach its more maintainable for our development work(it’s totally declarative)"
* what I like in vega is that it also works with Jupyter notebooks https://altair-viz.github.io/getting_started/overview.html
* for using vega with react we want to look at https://github.com/vega/react-vega

**Comment by kjgarza** [comment]
comparison of libraries in https://github.com/kjgarza/talk-react-d3

**Comment by kjgarza** [comment]
SSR evaluation in https://github.com/datacite/akita/pull/21 showed no problems for showing tooltips there

**Comment by kjgarza** [comment]
we will use Vega
