### ISSUE TITLE
Formatting issue with affiliation links in DataCite Commons record

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/akita#251]
#### Expected Behaviour

Two distinct ror affiliations associated with a creator should appear on separate lines

#### Current Behaviour

The links to two different affiliated organizations appears as one line

#### Steps to Reproduce

1. Go to https://commons.datacite.org/doi.org/10.14469/hpc/11109
2. see creator affiliation (no space between affiliated orgs)

![Screenshot 2022-11-15 at 11 45 26](https://user-images.githubusercontent.com/44582654/201911829-df0b0abc-5d35-4a63-a5ec-6961f7c93d4c.png)

### Context (Environment)

DataCite Commons

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3028l)

**Comment by hrzepa** [comment]
As of 7 February, the issue appears to continue
![Issue 251](https://user-images.githubusercontent.com/7828928/217180162-c41eab77-2a1e-4869-9743-56c8b6ec4e20.jpg)

**Comment by hrzepa** [comment]
Sorry, wrong image
[Issue 251.pdf](https://github.com/datacite/akita/files/10672605/Issue.251.pdf)

**Comment by hrzepa** [comment]
As of 7 Feb,  the issue does not appear to be resolved
![Issue 251](https://user-images.githubusercontent.com/7828928/217181259-f08f684e-d106-4ea4-91de-52585cbc8fb4.jpg)

**Comment by codycooperross** [comment]
@hrzepa Thank you for your message. Issues are sometimes closed by automatic processes and then reopened pending release. The technical team has looked at this issue and deployed a change to address it. You should see this reflected at https://commons.datacite.org now. Please contact support@datacite.org for any additional support needs.
