### ISSUE TITLE
Metadata 4.5 - Expanded support for new publisher values in GraphQL API/Akita

### ISSUE THREAD

**Issue by codycooperross** [datacite/akita#310]
**Modify GraphQL response for works to include new publisher values**

- [x] Make modifications in lupo to support requesting new publisher values in GraphQL queries

**Modify akita to support new publisher values**

- [x] Modify akita templates and queries to support new GraphQL query structure for publisher 

Needs PRs: https://github.com/datacite/akita/pull/315, https://github.com/datacite/lupo/pull/1075

**Comment by svogt0511** [comment]
Will be released February 25, 2024.
