### ISSUE TITLE
Allow queries and filtering of works by person or organization

### ISSUE THREAD

**Issue by mfenner** [datacite/akita#53]
![Bildschirmfoto 2020-07-20 um 06.26.48.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/b1789c9e-ff04-4644-9079-36370abe74b5)

The GraphQL API allows basically the same functionality of a listing of works by person, as it does for the general listing of works. We should, therefore, implement this in the same way in the UI. This includes:

* show number of results, i.e. `5 Works` instead of `Works` in this example
* show 25 results per page
* show a search box for works
* show facets and support filtering

This also aligns with how the listing of works is implemented in the current Researcher Profile in Fabrica.

**Comment by kjgarza** [comment]
Facets for supporting filtering was a Feature already discussed in the product design and it was scrapped from the MVP (see https://docs.google.com/document/d/1QqlFSeaLAPVfZkSy0Xn6u1PnBIdFNVJ79U3kp65BNo0/edit#heading=h.hys9mdq63yqu ). Having said that, It should be considered in future releases.


The number of results its already present three times in the page (i.e., Dois Production chart, Top counters, Type chart). It doubt the user needs to be reminded again that they have X amount of works. Do you still feel the user needs to be told again. 


A search box for the list of related content problaby needs further discussion this was not part of the original design.
