### ISSUE TITLE
Cypress report coverage seems inconsistent with test coverage

### ISSUE THREAD

**Issue by kjgarza** [datacite/akita#58]
## Description
Coverage report does not change when adding new test in certain component.

one can see that test included checks for each element and the coverage report doesn't change when removing them. E.g. https://github.com/datacite/akita/blob/0560f3b78be9f646c864d5c433dd5625bb2b19dc/src/components/CitationsChart/CitationsChart.test.tsx#L57

- [ ] Review configuration
- [ ] How is the coverage computed.

**Comment by kjgarza** [comment]
@mfenner is there any reason to keep this open? I think it was clear that the reporter inconsistence is because one needs to write `integration` test to test the component; as the component `unit` test are not enough for the reporter

**Comment by mfenner** [comment]
I am not sure this is clear and it needs more investigation.

**Comment by mfenner** [comment]
This has been addressed.
