### ISSUE TITLE
List view for DOIs is misaligned

### ISSUE THREAD

**Issue by mfenner** [datacite/akita#69]
![Bildschirmfoto 2020-08-04 um 23.03.08.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/3defde98-41d2-45ad-8a13-e899de6044d1)

**Comment by kjgarza** [comment]
fixed in https://github.com/datacite/akita/commit/a406bc2f9b2e0bc24d2b0c285135d28d6bc52042
