### ISSUE TITLE
Navigation from page for single work, person or organization

### ISSUE THREAD

**Issue by mfenner** [datacite/akita#76]

**Comment by richardhallett** [comment]
As discussed on the PR for this work, remaining work is to add visual cue to what is the current active search.

**Comment by mfenner** [comment]
Should that visual cue also be shown for a search about to start?

**Comment by richardhallett** [comment]
yes I think that would make sense as otherwise you don't know what is the default until you search.

**Comment by richardhallett** [comment]
Changes were made, closing as done.
