### ISSUE TITLE
Display of organizations

### ISSUE THREAD

**Issue by mfenner** [datacite/akita#8]
* using the GraphQL API for ROR. 
* he initial information shown can be aligned with what the ROR frontend is showing.
* also includes facets for types and countries
* cursor-based pagination
* for the detail view show content (dois) associated with the organization

**Comment by richardhallett** [comment]
Unsure if this is a bug or intended to be a different attribute, but "type" on graphQL appears to return "Organization" as opposed to defined type in ROR.

**Comment by richardhallett** [comment]
Can not support Filtering by Org Type currently as need changes to api see #62

**Comment by mfenner** [comment]
This issue has been fully addressed.
